services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysqlData:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=300M
    # restart: always
    ports:
      - 8083:80
